name: Node JS install
description: Install Node.JS and dependencies

runs:
  using: composite
  steps:
    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'

    - name: Cache dependencies
      id: node-cache
      uses: actions/cache@v3
      with:
        path: |
          node_modules
        key: node_modules-${{ hashFiles('package-lock.json') }}

    - name: Install dependencies
      if: ${{ !steps.node-cache.outputs.cache-hit }}
      shell: bash
      run: npm ci --ignore-scripts
